version: "3"

services:
  api:
    container_name: backend
    image: node:10
    networks:
      - db
      - frontend
    ports:
      - "3000:3000"
    command: sh -c "npm install && npm run dev"
    # command: sh -c "yarn && ./node_modules/.bin/pm2-runtime start pm2-dev.config.js"
    depends_on:
      - db
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      MONGODB_URL: db

  db:
    container_name: mongodb
    image: mongo
    networks:
      - db
    volumes:
      - db_data:/data/db
      - ./database-dump:/database-dump
    ports:
      - "27017:27017"
    environment:
      MONGODB_USER: root
      MONGODB_PASS: root
      MONGO_DATA_DIR: /data/db


networks:
  db:
  frontend:

volumes:
  db_data:

